name: Main Branch Docker Image CI

on:
  schedule:
    - cron:  '* 12 * * 6'

jobs:
  test_schedule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the TF Docker image
      run: |
        cd cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/tf_serving
        docker build -f gramine_tf_serving.dockerfile . -t tf_serving:latest
        docker images
        docker rmi tf_serving:latest
        
    - name: Build the SP Docker image
      run: |
        cd cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/secret_prov
        docker build -f secret_prov.dockerfile . -t sp_serving:latest
        docker images
        docker rmi sp_serving:latest

    - name: Build the gRPC-TLS Docker image
      run: |
        cd cczoo/grpc-ra-tls/docker/gramine
        docker build -f grpc-gramine-sgx-dev.dockerfile . -t grpc-tls:latest
        docker images
        docker rmi grpc-tls:latest
      
